name: "Release"

on:
  push:
    branches:
      - main

jobs:
  node:
    uses: timayz/.github/.github/workflows/node-release.yml@v3
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
